src/main/java/com/playdata/eungae/HomeController.java
=> Feat: HomeController를 생성하였습니다.

src/main/resources/static/css/hospital-details.css, src/main/resources/static/js/hospital-details.js, src/main/resources/templates/find-hospital.html, src/main/resources/templates/hospital-details.html
=> [FE] Feat: 병원 상세 페이지 프론트 작성

src/main/resources/static/css/community.css, src/main/resources/static/css/medical-records.css, src/main/resources/static/js/medical-records.js, src/main/resources/templates/community.html, src/main/resources/templates/medical-records.html
=> [FE] Feat: 커뮤니티 글목록 페이지 작업

src/main/resources/static/css/community-write.css, src/main/resources/templates/community-write.html
Feat: 커뮤니티 글쓰기 페이지 작업 완료했습니다
This closes #31
=> [FE] Feat: 커뮤니티 글쓰기 페이지 작업

src/main/resources/static/css/my-page.css, src/main/resources/templates/my-page.html
=> [FE] Feat: 마이페이지 개발하기

src/main/resources/static/css/community-post-details.css, src/main/resources/templates/community-post-details.html
Feat: 커뮤니티 게시글 상세보기 페이지 작업 완료했습니다
This closes #45
=> [FE] Feat: 커뮤니티 게시글 상세보기 페이지 작업

src/main/resources/static/css/medical-records.css, src/main/resources/static/js/medical-records.js, src/main/resources/templates/medical-records.html
Feat: 내 예약 확인 페이지 작업 완료했습니다
This closes #49
=> [FE] Feat: 내 예약 확인 페이지 작업

src/main/resources/static/css/my-reservations.css, src/main/resources/templates/my-reservations.html
Feat: 진료내역 확인 페이지 작업
This closes #21
=> [FE] Feat: 진료내역 확인 페이지 작업

src/main/resources/templates/my-page.html
[FE] Fix: 마이페이지 css 경로 수정을 완료했습니다. 
기존 경로가 들어가 있었는데 변경한 경로는 제대로 잡힙니다.
This closes #44
=> [FE] Fix: 마이페이지 css 경로 수정

src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java, src/main/java/com/playdata/eungae/community/presentation/CommunityViewController.java, src/main/java/com/playdata/eungae/hospital/presentation/HospitalViewController.java, src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
Feat: 패키지 구조 설계 작업했습니다.
This closes #58
=> [BE] Feat: 패키지 구조 설계 작업

src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
Feat : hospital entity 추가 작업 완료했습니다.
This closes #68
=> [BE] Feat : Hospital entity 추가

src/main/java/com/playdata/eungae/hospital/domain/Doctor.java
Feat : doctor entity 추가 작업 완료했습니다.
This closes #69
=> [BE] Feat : Doctor entity 추가

src/main/java/com/playdata/eungae/member/domain/Member.java
[BE] Feat: Member Entity 개발
This closes #55
=> [BE] Feat: Member Entity 개발

src/main/java/com/playdata/eungae/EungaeApplication.java, src/main/java/com/playdata/eungae/base/BaseEntity.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
Base Entity 작성을 완료하였습니다.
This closes #79
=> [BE] Feat: Base Entity 작성

src/main/java/com/playdata/eungae/review/domain/Review.java, src/main/java/com/playdata/eungae/review/presentation/ReviewViewController.java
Feat: Review Entity 작업 완료했습니다
This closes #81
=> [BE] Feat: Review Entity 생성

src/main/java/com/playdata/eungae/doctor/application/DoctorClosed.java, src/main/java/com/playdata/eungae/doctor/presentation/DoctorViewController.java
doctor_closed 엔티티 작성 완료했습니다
This closes #82
=> [BE] Feat: DoctorClosed 엔티티 생성

src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
[BE] Feat: hospital_schedule 엔티티 생성
This closes #61
=> [BE] Feat: hospital_schedule 엔티티 생성

src/main/java/com/playdata/eungae/appointment/domain/AppointmentDocument.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
[[BE] Feat: appointment document 엔티티 생성
=> [BE] Feat: AppointmentDocument 엔티티 생성

src/main/java/com/playdata/eungae/appointment/domain/AppointmentDocument.java, src/main/java/com/playdata/eungae/community/domain/CommunityBoard.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
[[BE] Feat: CommunityBoard 엔티티 생성](https://github.com/team-eungae/eungae-pediatric_appointment/issues/65)
=> [BE] Feat: CommunityBoard 엔티티 생성

src/main/java/com/playdata/eungae/appointment/domain/repository/Appointment.java
기존 `@ColumnDefault()`로 insert시 기본값이 적용되는 줄 알았던 것을 멘토님이 해당 어노테이션은 ddl-auto가 create일 시에만 적용되는 것이라고 리뷰 주셨기에 `@DynamicInsert` 어노테이션을 추가하여서 원래 의도대로 동작하도록 하였습니다.
This closes #66
=> [BE] Feat: Appointment 엔티티를 완료하였습니다.

src/main/java/com/playdata/eungae/appointment/domain/repository/Appointment.java, src/main/java/com/playdata/eungae/hospital/domain/repository/HospitalImage.java
HospitalImage 엔티티 작업을 완료했습니다. 현재는 그냥 엔티티의 필드만 정의헀을 뿐이고 연관관계 매핑 및 정리는 이후에 하는 걸로 했습니다.
This closes #62
=> [BE] Feat: HospitalImage 엔티티를 완료했습니다.

src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
[BE] Fix: HospitalImage Entity 파일 위치 변경
This closes #96
=> [BE] Fix: HospitalImage Entity 파일 위치 변경

src/main/java/com/playdata/eungae/HomeController.java, src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java, src/main/java/com/playdata/eungae/article/presentation/ArticleViewController.java, src/main/java/com/playdata/eungae/community/presentation/CommunityViewController.java, src/main/java/com/playdata/eungae/hospital/presentation/HospitalViewController.java, src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
Feat: @Controller로 기능 화면 연결 작업했습니다.
This closes #59
=> [BE] Feat: @Controller로 기능 화면 연결

src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
Entity 패키지 수정 및 dummy.txt 파일 삭제를 완료했습니다.
This closes #104
=> [BE] Fix: Entity 패키지 수정 및 dummy.txt 파일 삭제

README.md
=> [ALL] Docs: README.md 수정

build.gradle, src/main/resources/application.yml
[BE] Chore: application.yml, build.gradle 수정완료
This closes #108
=> [BE] Chore: application.yml, build.gradle 수정하여 DB 접근 로직 생성

src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/appointment/domain/AppointmentDocument.java, src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java, src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java, src/main/java/com/playdata/eungae/article/presentation/ArticleViewController.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java, src/main/java/com/playdata/eungae/doctor/domain/DoctorSchedule.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java, src/main/java/com/playdata/eungae/member/domain/Children.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/review/domain/Review.java
Entity들의 연관관계를 설정하고 불필요한 import문을 정리했습니다.
#110 pr을 받은 이후에 #106 남은 인수조건을 마무리 하겠습니다.
=> [BE] Feat: Entity들의 연관관계를 설정하고 불필요한 import문을 정리했습니다.

src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
[BE] Fix: DoctorClosed 엔티티의 id 수정완료했습니다
This closes #114
=> [BE] Fix: DoctorClosed 엔티티 변수명 수정

src/main/resources/static/css/sign-up.css, src/main/resources/static/js/sign-up.js, src/main/resources/templates/contents/member/sign-up.html
[FE] Feat: 회원가입 비밀번호 유효성 검사 구현
This closes #109
=> [FE] Feat: 회원가입 비밀번호 유효성 검사 구현

src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
[BE] Fix: DoctorClosed 엔티티 컬럼명 수정
This closes #125
=> [BE] Fix: DoctorClosed 엔티티 컬럼명 수정

src/main/java/com/playdata/eungae/hospital/domain/HospitalClosed.java
[BE] Feat: HospitalClosed 엔티티 작성
This closes #123
=> [BE] Feat: HospitalClosed 엔티티 작성

src/main/java/com/playdata/eungae/HomeController.java, src/main/resources/static/css/login.css, src/main/resources/templates/contents/member/login.html
로그인 페이지 개발을 완료 했습니다.
This closes #92
=> [FE] Feat: 로그인 페이지 개발

src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java, src/main/resources/static/css/medical-records-details.css, src/main/resources/static/js/medical-records.js, src/main/resources/templates/contents/member/medical-records-details.html, src/main/resources/templates/contents/member/medical-records.html
[ALL] Feat: 내 진료기록 열람 페이지 생성 및 컨트롤러 매핑 완료했습니다 
This closes #131
=> [ALL] Feat: 내 진료기록 열람 페이지 생성 및 컨트롤러 매핑

src/main/resources/static/css/hospital-details.css, src/main/resources/static/css/my-review.css, src/main/resources/templates/contents/hospital/hospital-details.html, src/main/resources/templates/contents/member/my-review.html, src/main/resources/templates/fragments/hospitalBottomNavbar.html, src/main/resources/templates/layouts/hospital_layout.html
Feat: 병원 상세 리뷰 목록 구현 및 컨트롤러 매핑 및 css 수정 작업했습니다.
This closes #119
=> [ALL] Feat: 병원 상세 리뷰 목록 구현 및 컨트롤러 매핑

.gitignore
.gitignore 수정 완료, 지속적으로 수정할 예정
This closes #47
=> [ALL] Chore: .gitignore 수정

src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
=> [BE] Fix: 엔티티 수정

src/main/resources/static/css/my-page-form.css, src/main/resources/static/js/my-page-form.js, src/main/resources/templates/contents/member/my-page-form.html
=> [ALL] Feat: 내 정보 수정 페이지 화면 개발 및 컨트롤러 매핑

src/main/resources/static/css/my-page.css, src/main/resources/static/js/my-page.js, src/main/resources/templates/contents/member/my-page.html
[ALL] Feat: 회원 탈퇴하기 페이지 및 컨트롤러 매핑
This closes #120
=> [ALL] Feat: 회원 탈퇴하기 페이지 및 컨트롤러 매핑

src/main/java/com/playdata/eungae/review/presentation/ReviewViewController.java, src/main/resources/static/css/my-page.css, src/main/resources/static/css/review-write.css, src/main/resources/static/js/my-page.js, src/main/resources/templates/contents/member/my-page.html, src/main/resources/templates/contents/member/review-write.html
[ALL] Feat: 내 리뷰 작성 페이지 및 컨트롤러 매핑
=> [ALL] Feat: 내 리뷰 작성 페이지 및 컨트롤러 매핑

src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java, src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
패키지 구조를 레이어드 아키텍쳐 방식으로 바꾸기
This closes #143
=> [BE] Feat: 패키지 구조를 레이어드 아키텍쳐 방식으로 바꾸기

src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java, src/main/java/com/playdata/eungae/review/domain/Review.java, src/main/java/com/playdata/eungae/review/dto/RequestReviewFormDto.java, src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java, src/main/java/com/playdata/eungae/review/repository/ReviewRepositoryImpl.java, src/main/java/com/playdata/eungae/review/service/ReviewService.java, src/main/java/com/playdata/eungae/review/service/ReviewServiceImpl.java
=> [BE] Fix : Entity 내부 스펙 변경

src/main/java/com/playdata/eungae/initDB.java
=> [BE] Feat : Test 더미데이터를 추가하기 위한 PostConstruct 추가

src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java, src/main/java/com/playdata/eungae/member/repository/MemberRepository.java, src/main/java/com/playdata/eungae/member/service/MemberService.java
자체 회원가입 기능 스케치 개발
아직 완료 안됐습니다 !
=> [BE] Feat: 자체 회원가입 기능 스케치 개발

.gitignore, src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
[BE] Feat: Spring Security 추가 및 Config 설정
=> [BE] Feat: Spring Security 추가 및 Config 설정

src/main/java/com/playdata/eungae/config/WebSecurityConfig.java, src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java, src/main/java/com/playdata/eungae/member/repository/MemberRepository.java, src/main/java/com/playdata/eungae/member/service/MemberService.java, src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java, src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
자체 회원가입 개발
이후에 테스트 코드 작성해서 이슈에 인수조건에 맞는지 검증할 예정입니다.
Issue number #156
=> [BE] Feat: 자체 회원가입 개발

src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java, src/main/java/com/playdata/eungae/review/service/ReviewService.java, src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
ResponseStatus 적용
고아객체 제거 옵션 삭제
=> [BE] Refactor : Review Service 리팩토링

build.gradle, src/main/java/com/playdata/eungae/member/controller/ChildrenController.java, src/main/java/com/playdata/eungae/member/domain/Children.java, src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java, src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java, src/main/java/com/playdata/eungae/member/service/ChildrenService.java, src/main/resources/static/js/my-children-add.js, src/main/resources/templates/contents/member/my-children-add.html, src/main/resources/templates/contents/member/my-children.html
[BE] Feat: 자녀 추가, 삭제 기능 및 성별 추가.
사진 추가는 리스트로 안 넘어와서 추후에 수정 예정.
=> [BE] Feat: 자녀관리 기능 개발

src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
[BE] Fix: Appointment 엔티티의 Date 타입을 LocalDateTime으로 수정
This closes #176
=> [BE] Fix: Appointment 엔티티

src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/member/dto/MemberFindResponseDto.java, src/main/java/com/playdata/eungae/member/dto/MemberUpdateRequestDto.java, src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java, src/main/java/com/playdata/eungae/member/service/MemberService.java, src/main/resources/templates/contents/member/my-page.html
[BE] Feat: 마이페이지 구현
This closes #174
=> [BE] Feat: 마이페이지 구현

src/main/java/com/playdata/eungae/member/domain/Member.java
[BE] Fix: Member 엔티티 @Builder 중복 수정
=> [BE] Fix: Member 엔티티 @Builder 중복 수정

src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalRegisterRequestDto.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalScheduleRequestDto.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalScheduleViewResponseDto.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalScheduleRepository.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/test/java/com/playdata/eungae/hospital/service/HospitalServiceImplTest.java
Feat: 병원, 병원 스케줄 생성 기능 구현했습니다.
This closes #164.
=> [BE] Feat: 병원, 병원 스케줄 생성 기능 구현

src/main/java/com/playdata/eungae/HomeController.java, src/main/java/com/playdata/eungae/config/WebSecurityConfig.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java, src/main/java/com/playdata/eungae/member/service/MemberService.java, src/main/resources/static/js/sign-up.js, src/main/resources/templates/contents/member/sign-up.html, src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java, src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
[BE] Feat: 회원가입 실행 테스트
This closes #156
This closes #167
=> [BE] Feat: 회원가입 실행 테스트

src/main/resources/static/css/hospital-details.css, src/main/resources/static/js/hospital-details.js, src/main/resources/templates/contents/hospital/hospital-details.html
Feat: 병원 상세보기 페이지 DB데이터 적용 구현했습니다. 리뷰 목록은 추가할 예정입니다.
=> [FE] Feat: 병원 상세보기 페이지 DB데이터 적용

src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java, src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/dto/MemberUpdateRequestDto.java, src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java, src/main/java/com/playdata/eungae/member/repository/MemberRepository.java, src/main/java/com/playdata/eungae/member/service/MemberService.java, src/main/resources/static/css/my-page-form.css, src/main/resources/static/css/notice-list.css, src/main/resources/static/js/my-page-form.js, src/main/resources/static/js/my-page.js, src/main/resources/templates/contents/member/my-page-form.html, src/main/resources/templates/contents/member/my-page.html, src/main/resources/templates/contents/notice/notice-list.html
[BE] Feat: 회원 정보 수정 기능 구현
This closes #162
=> [BE] Feat: 회원 정보 수정 기능 구현

src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java, src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
[BE] Feat: 병원 상세보기 의사 메소드 수정했습니다.
=> [BE] Feat: 병원 상세보기 기능 구현

src/main/java/com/playdata/eungae/initDB.java, src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
[BE] Feat: initDB dummy 데이터 생성
=> [BE] Feat: initDB dummy 데이터 생성

src/main/java/com/playdata/eungae/admin/controller/AdminController.java, src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/appointment/domain/AppointmentStatus.java, src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/java/com/playdata/eungae/initDB.java, src/main/java/com/playdata/eungae/member/controller/ChildrenController.java, src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java, src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java, src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java, src/main/java/com/playdata/eungae/member/service/ChildrenService.java, src/main/resources/application.yml, src/main/resources/static/css/appointment.css, src/main/resources/static/js/appointment.js, src/main/resources/static/js/map.js, src/main/resources/templates/contents/appointment/appointment.html, src/main/resources/templates/contents/hospital/hospital-details.html, src/test/java/com/playdata/eungae/hospital/service/HospitalServiceImplTest.java
[BE] Feat: 예약을 위한 세팅 및 공공데이터 파싱 코드 작성
=> [BE] Feat: 예약을 위한 세팅 및 공공데이터 파싱 코드 작성

src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
[BE] Feat: 내 주변 병원 찾기 API 개발했습니다
This closes #209
=> [BE] Feat: 내 주변 병원 찾기 API 개발

src/main/java/com/playdata/eungae/config/SpringConfig.java, src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java, src/main/java/com/playdata/eungae/doctor/service/DoctorService.java, src/main/java/com/playdata/eungae/file/FileStore.java, src/main/java/com/playdata/eungae/file/ResultFileStore.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalImageResponseDto.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalImageRepository.java, src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/java/com/playdata/eungae/initDB.java, src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java, src/main/java/com/playdata/eungae/review/dto/ResponseReviewDto.java, src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java, src/main/java/com/playdata/eungae/review/service/ReviewService.java, src/main/resources/application.yml, src/main/resources/static/css/hospital-details.css, src/main/resources/static/js/hospital-details.js, src/main/resources/static/js/map.js, src/main/resources/templates/contents/hospital/create-doctor.html, src/main/resources/templates/contents/hospital/hospital-details.html
Feat:  의사, 병원 이미지 파일 업로드, 의사 생성 기능 구현 및 화면 연결했습니다.
This closes #212
=> [ALL] Feat: 의사, 병원 이미지 파일 업로드, 의사 생성 기능 구현 및 화면 연결

src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/config/SpringConfig.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/initDB.java
=> [BE] Feat: Merge 후 오류 수정

src/main/java/com/playdata/eungae/config/FileUploadConfig.java, src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorViewResponseDto.java, src/main/java/com/playdata/eungae/doctor/service/DoctorService.java, src/main/java/com/playdata/eungae/file/FileStore.java, src/main/java/com/playdata/eungae/file/ResultFileStore.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java, src/main/java/com/playdata/eungae/initDB.java, src/main/resources/application.yml
=> [BE] Fix: 이미지 업로드 코드 리팩토링

src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java, src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java, src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java, src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java, src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java, src/main/resources/templates/contents/community/community-list.html, src/main/resources/templates/contents/community/community-write.html
=> [BE] Feat: CommunityBoard 개발

src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
[BE] Feat: 병원 검색 API 개발
This closes #223
=> [BE] Feat: 병원 검색 API 개발

src/main/resources/static/css/hospital-details.css, src/main/resources/static/js/hospital-details.js, src/main/resources/templates/contents/hospital/hospital-details.html
Feat: 병원 상세페이지 이미지 슬라이드 구현했습니다.
This closes #228
=> [FE] Feat: 병원 상세페이지 이미지 슬라이드 구현

src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java
=> [BE] Fix: 공지사항 목록 및 공지사항 상세 기능 수정

src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/resources/static/css/review-write.css, src/main/resources/templates/contents/member/my-review.html, src/main/resources/templates/contents/member/review-write.html
Feat: 내 리뷰목록 페이지 화면 매핑
This closes #236
=> [ALL] Feat: 내 리뷰목록 페이지 화면 매핑

src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/initDB.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
=> [BE] Fix: 병합 이후 오류 수정

src/main/resources/static/css/hospital-details.css, src/main/resources/static/js/hospital-details.js, src/main/resources/templates/contents/hospital/hospital-details.html
병원 상세 페이지 즐겨찾기 버튼 추가했습니다.
This closes #253
=> [FE] Feat: 병원 상세 페이지 즐겨찾기 버튼 추가

src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java, src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java, src/main/java/com/playdata/eungae/appointment/dto/RequestAppointmentDeleteDto.java, src/main/java/com/playdata/eungae/appointment/dto/ResponseAppointmentDto.java, src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java, src/main/java/com/playdata/eungae/appointment/dto/ResponseMedicalHistoryDto.java, src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java, src/main/resources/static/css/medical-records.css, src/main/resources/static/css/my-reservations.css, src/main/resources/static/js/my-reservations.js, src/main/resources/templates/contents/member/medical-records-details.html, src/main/resources/templates/contents/member/medical-records.html, src/main/resources/templates/contents/member/my-reservations.html, src/main/resources/templates/contents/member/my-review.html, src/main/resources/templates/contents/member/review-write.html
reivew 논리적 삭제 컬럼 구현 필요
This closes #194 
This closes #204 
This closes #203
=> [ALL] Feat : 내 예약 조회, 예약 취소, 리뷰 등록, 진료내역 조회 개발 완료

src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/main/java/com/playdata/eungae/member/service/MemberService.java
마이페이지 및 회원정보수정 기능 수정했습니다.
This closes #243
=> [BE] Fix: 마이페이지 및 회원정보 수정 기능 수정

src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/config/WebConfig.java, src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorResponseDto.java, src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java, src/main/java/com/playdata/eungae/doctor/service/DoctorService.java, src/main/java/com/playdata/eungae/file/FileStore.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java, src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java, src/main/java/com/playdata/eungae/initDB.java
Fix: 이미지 코드 리팩토링했습니다.
This closes #248
=> [BE] Fix: 이미지 코드 리팩토링

src/main/resources/static/js/map.js
[FE] Feat: 병원 검색결과 프론트 연결
This closes #227
=> [FE] Feat: 병원 검색결과 프론트 연결

src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
[BE] Feat: CommunityBoardController 추가
=> [BE] Feat: CommunityBoard Controller 누락된 거 다시 PR

src/main/resources/static/js/map.js
[FE] Feat: 병원 검색시 프론트에서 공백확인
This closes #258
=> [FE] Feat: 병원 검색시 공백확인

src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/member/controller/MemberApiController.java, src/main/java/com/playdata/eungae/member/repository/FavoritesHospitalRepository.java, src/main/java/com/playdata/eungae/member/service/MemberService.java, src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java, src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java, src/main/java/com/playdata/eungae/review/service/ReviewService.java, src/main/resources/static/js/hospital-details.js
appointment의 status가 diagnosis 가 아니면 exception 발생하도록 코드 수정
Repository에서 바로 최신순으로 정렬해서 배열을 반환하도록 작업
=> [ALL] Refactor : review, appointment 코드 리펙터링

src/main/resources/static/js/map.js
[ALL] Fix: 주변 병원검색 latitude와 longtude 변경
This closes #270
=> [ALL] Fix: 주변 병원검색 latitude와 longtude 변경

src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java, src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java, src/main/java/com/playdata/eungae/member/controller/ChildrenController.java, src/main/resources/static/js/community-list.js, src/main/resources/templates/contents/community/community-list.html, src/main/resources/templates/contents/community/community-post-details.html, src/main/resources/templates/contents/community/community-write.html, src/main/resources/templates/contents/member/my-children-add.html, src/main/resources/templates/fragments/bottomNavbar.html
[BE] Feat: CommunityBoard 맵핑, 글쓰기, 삭제, 상세보기 개발 및 자녀 기능 수정
요구사항 명세서에 맞게 맵핑명 수정했습니다.
=> [BE] Feat: CommunityBoard 맵핑,글쓰기, 삭제, 상세보기 개발 및 자녀 기능 수정

src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/domain/Children.java, src/main/resources/static/css/appointment.css, src/main/resources/static/js/appointment.js, src/main/resources/templates/contents/appointment/appointment.html
appointment 창에서 children이 같은 날짜에 예약 못하는 기능 추가
=> [ALL] Feat : appointment 창에서 정보 수정시 api 요청 보내도록 수정

src/main/resources/static/js/map.js
[FE] Fix: 카카오맵 마커 오버레이 에러 수정
This closes #276
=> [FE] Fix: 카카오맵 마커 오버레이 에러 수정

src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java, src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/resources/static/js/appointment.js, src/main/resources/templates/contents/appointment/appointment.html
예약 저장 RestController로 변경
예약 저장 전 유효성 검사 추가
=> [ALL] Feat : 유효성 검사 추가

src/main/java/com/playdata/eungae/member/dto/ResponseFavoritesHospitalDto.java, src/main/resources/static/css/regular-hospital.css, src/main/resources/templates/contents/member/regular-hospital.html
Feat: 단골 병원 DB 데이터 연결
This closes #281
=> [ALL] Feat: 단골 병원 DB 데이터 화면과 연결

src/main/resources/static/css/main.css, src/main/resources/templates/index.html
메인페이지 화면 수정했습니다.
This closes #284
=> [FE] Fix: 메인페이지 화면 수정

src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
[BE] Feat: 병원 키워드검색 유효성 검사
#287
=> [BE] Feat: 병원 키워드검색 유효성 검사

src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
=> [BE] Refactor: 코드 포맷팅 및 리뷰 사항 반영

src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/resources/static/css/hospital-main.css, src/main/resources/templates/hospital-contents/hospital-admin.html
병원 메인 페이지 View만 개발 완료
This closes #268
=> [BE] Feat: 병원 메인 페이지 View 개발

src/main/resources/templates/index.html
메인페이지 버튼 연결 수정했습니다.
This closes #301
=> [FE] Fix: 메인페이지 버튼 연결 수정

src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java, src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
우선 주석처리 후 이후에 테스트 코드들을 전부 지우던지 아니면 컴파일 에러를 잡든지 하는 방향으로 수정하긴 해야 될 것 같습니다.
this closes #305
=> [BE] Fix: AWS 배포 후 gradle 빌드 도중 작성된 Test 코드에서 컴파일 에러가 발생했습니다.

src/main/resources/static/js/map.js
[FE] Feat: 다른 마커 선택시 다른 오버레이 지우기
This closes #303
=> [FE] Feat: 다른 마커 선택시 다른 오버레이 지우기

src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java, src/main/resources/templates/contents/member/sign-up.html
`input` 태그 안에 숫자만 입력하여도 Dto에서 변환하는 메서드를 통해 DB에 들어가는 건 형식을 맞춰서 들어가도록 변경
This closes #308
=> [BE] Fix: 회원가입 정규 표현식 추가

src/main/java/com/playdata/eungae/member/service/ChildrenService.java
=> [BE] Fix: 병합 후 오류 수정

src/main/java/com/playdata/eungae/initDB.java
=> [BE] Feat: initDB 수정

src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/dto/KeywordSearchRequestDto.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/resources/static/js/map.js
[ALL] Feat: 병원 검색 이후 지도 중심 변경
This closes #300 
키워드 검색시 위도, 경도가 필요해서 DTO를 만들어서 처리했습니다
=> [ALL] Feat: 병원 검색 이후 지도 중심 변경

src/main/resources/static/js/map.js, src/main/resources/templates/contents/hospital/hospital-details.html
[FE] Feat: hospital의 addressDetail 필드가 thymeleaf에서 랜더링 되지 않게 수정
closes #328
=> [FE] Feat: hospital의 addressDetail 필드가 thymeleaf에서 랜더링 되지 않게 수정

src/main/resources/templates/contents/hospital/hospital-details.html
=> [FE] Refactor: 이미지 슬라이드 수정

src/main/resources/static/css/appointment.css, src/main/resources/templates/contents/appointment/appointment.html
=> [FE] Fix: 의사 기본 이미지 처리

src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java, src/main/java/com/playdata/eungae/config/SpringConfig.java, src/main/java/com/playdata/eungae/config/WebSecurityConfig.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java, src/main/resources/application.yml
병합 과정에서 발생한 에러 해결 및 Entity를 View에 직접 반환하는 로직을 변경하였습니다,
=> [BE] Fix: 병합 과정에서 발생한 에러 해결 및 Entity를 View에 직접 반환하는 로직 변경

src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/resources/static/js/appointment.js
예약 현재 시간 이전 시간 비활성화
This closes #338
=> [ALL] Feat: 예약 현재 시간 이전 시간 비활성화

src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java, src/main/resources/static/css/community-list.css, src/main/resources/static/css/medical-records-details.css, src/main/resources/templates/contents/community/community-edit.html, src/main/resources/templates/contents/community/community-list.html, src/main/resources/templates/contents/community/community-post-details.html, src/main/resources/templates/contents/member/regular-hospital.html
Fix: 커뮤니티 css, 매핑 오류 수정
This closes #340
=> [ALL] Fix: 커뮤니티 css, 매핑 오류 수정

src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/domain/DoctorStatus.java, src/main/java/com/playdata/eungae/doctor/dto/DoctorResponseDto.java
DoctorStatus 엔티티 추가했습니다 .
This closes #343
=> [BE] Feat: DoctorStatus 엔티티 추가

src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java, src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
=> [BE] Fix: 병합 후 발생하는 에러 수정

build.gradle, src/main/java/com/playdata/eungae/admin/controller/AdminController.java, src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/config/RedisConfig.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/resources/application.yml
[BE] Feat: 주변 병원검색시 Redis에서 조회 작업 완료했습니다
1. redis.conf 파일에서 비밀번호를 eungae 로 설정해야합니다
2. 캐싱 전략이 정해지지 않아서 우선 병원 전체조회 후 캐시에 저장하는 메소드를 만들고 작업했습니다
This closes #345
=> [BE] Feat: 주변 병원검색시 Redis에서 조회

src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java, src/main/java/com/playdata/eungae/appointment/domain/Appointment.java, src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java, src/main/java/com/playdata/eungae/appointment/dto/RequestAppointmentDeleteDto.java, src/main/java/com/playdata/eungae/appointment/dto/ResponseMedicalHistoryDto.java, src/main/resources/application.yml
[BE] Kakao Api 인증키 추가 및 코드 포맷팅
=> [BE] Style: Kakao Api 인증키 추가 및 코드 포맷팅

src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java, src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java, src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java, src/main/java/com/playdata/eungae/base/BaseEntity.java, src/main/java/com/playdata/eungae/doctor/domain/Doctor.java, src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalImageRepository.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java, src/main/java/com/playdata/eungae/hospital/repository/HospitalScheduleRepository.java, src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java, src/main/java/com/playdata/eungae/member/repository/MemberRepository.java, src/main/java/com/playdata/eungae/member/service/ChildrenService.java, src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java, src/main/java/com/playdata/eungae/review/service/ReviewService.java
Feat: 논리 삭제로 변경하면서 조회도 변경
This closes #356
=> [FE] Feat: 논리 삭제 변경

src/main/java/com/playdata/eungae/HomeController.java, src/main/java/com/playdata/eungae/initDB.java, src/main/resources/application.yml, src/main/resources/static/css/map.css, src/main/resources/static/css/my-reservations.css, src/main/resources/static/js/map.js, src/main/resources/templates/contents/member/my-reservations.html
=> [BE] Style: 카카오맵 오버레이 스타일 변경 및 나의 예약 페이지 스타일 변경

build.gradle, src/main/java/com/playdata/eungae/config/SecurityConfig.java, src/main/java/com/playdata/eungae/member/controller/MemberViewController.java, src/main/java/com/playdata/eungae/member/domain/Member.java, src/main/java/com/playdata/eungae/security/KakaoUserInfo.java, src/main/java/com/playdata/eungae/security/MemberOAuthUserService.java, src/main/java/com/playdata/eungae/security/MemberUserDetails.java, src/main/java/com/playdata/eungae/security/MemberUserDetailsService.java, src/main/java/com/playdata/eungae/security/OAuthUserInfo.java, src/main/resources/application.yml, src/main/resources/static/js/kakao-login.js, src/main/resources/templates/contents/member/login.html
카카오 로그인 구현 완료
다만 현재 문제점은 카카오에서 제공하지 않는 값은 "정보를 입력해 주세요" 라는 값이 임의로 들어가도록 설정되어 있음.
이를 어떻게 해결할 것인지 논의 필요
closes #100
=> [BE] Feat: 카카오 로그인 구현 완료

src/main/resources/templates/contents/member/my-review.html
[FE] Fix: 내 리뷰목록에 제목이 뜨게 수정
This closes #366
=> [FE] Fix: 내 리뷰목록에 제목이 뜨게 수정

src/main/java/com/playdata/eungae/config/SecurityConfig.java
=> [BE] Fix: 로그인시 첫 번째 로그인일 경우 error 페이지가 랜더링 되는 에러 수정

src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java, src/main/java/com/playdata/eungae/appointment/dto/ResponsePaymentDto.java
String으로 받아서 LocalDate 타입으로 변경하도록 수정
=> [BE] Fix : 예약시 LocalDate 타입의 json 파싱이 안되는 버그 수정

src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java, src/main/java/com/playdata/eungae/hospital/service/HospitalService.java, src/main/resources/static/css/map.css, src/main/resources/static/js/map.js
[ALL] Feat: 병원 검색시 대기자 수 확인 작업 완료했습니다
This closes #368
=> [ALL] Feat: 병원 검색시 대기자 수 확인

src/main/java/com/playdata/eungae/initDB.java
=> [BE] Fix: initDb 컴파일 에러 수정

src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
HospitalService 수정
1. 병원 대기자 수 검색시 현재 시간이 오전 9시 30분보다 빠르면 조회하는데 문제가 있어서 수정했습니다. 
ex) 예약 시간 조회시 0730 으로 조회되어야 하는데 730으로 조회됨
2. if else 문을 줄여서 작업했습니다.
This closes #378
=> [BE] Fix: HospitalService 대기자 수 검색

src/main/java/com/playdata/eungae/config/RedisConfig.java, src/main/java/com/playdata/eungae/config/SecurityConfig.java, src/main/java/com/playdata/eungae/config/SpringConfig.java, src/main/java/com/playdata/eungae/initDB.java, src/main/resources/application.yml, src/main/resources/static/js/map.js
지도 오버레이 이미지 수정 및 레디스 환경 변수 변경
This closes #381, #382
=> [ALL] Fix: 지도 오버레이 이미지 수정 및 레디스 환경 변수 변경

src/main/resources/static/js/appointment.js
Fix: 예약 날짜 형식 에러 수정
This closes #386
=> [BE] Fix: 예약 날짜 형식 에러 수정

src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java, src/main/java/com/playdata/eungae/hospital/domain/Hospital.java, src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java, src/main/java/com/playdata/eungae/initDB.java, src/main/resources/static/js/map.js
Feat: 응애 서비스 이용하지 않는 병원 지도 정보 띄우기
This closes #388
=> [ALL] Feat: 응애 서비스 이용하지 않는 병원 지도 정보 띄우기

src/main/resources/static/js/map.js
[FE] Fix: 병원 키워드검색시 오류 수정
This closes #391
=> [FE] Fix: 병원 키워드검색시 오류 수정

src/main/resources/static/js/map.js
Fix: 지도 자바스크립트 오류 수정 및 검색 결과 없을 때 처리
This closes #393
=> [FE] Fix: 지도 자바스크립트 오류 수정 및 검색 결과 없을 때 처리

src/main/resources/static/css/hospital-details.css, src/main/resources/templates/contents/hospital/hospital-details.html
[FE] Fix: 병원 상세 수정했습니다.
This closes #396
=> [FE] Fix: 병원 상세 수정

src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
별점 계산 수정했습니다.
This closes #399
=> [BE] Fix: 별점 계산 수정

src/main/java/com/playdata/eungae/EungaeApplication.java, src/main/java/com/playdata/eungae/admin/RedisScheduler.java, src/main/java/com/playdata/eungae/admin/controller/AdminController.java, src/main/java/com/playdata/eungae/admin/service/AdminService.java, src/main/java/com/playdata/eungae/initRedis.java
[BE] Feat: 병원정보 레디스 캐싱처리
1. 어플리케이션 실행할 때 ddl-auto가 create로 설정되어 있으면 "hospital" 키가 초기화되게 작성하였습니다
2. 병원데이터를 DB에 저장하고 바로 레디스에 저장하도록 수정하였습니다
3. 스케줄러 사용해서 매일 새벽 2시에 레디스가 업데이트 되도록 작성하였습니다.
This closes #390
=> [BE] Feat: 병원정보 레디스 캐싱

src/main/resources/static/js/hospital-details.js, src/main/resources/templates/contents/hospital/hospital-details.html
Feat: 전화번호 복사 기능 구현했습니다.
This closes #406
=> [FE] Feat: 전화번호 복사 기능 구현
